
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('music').del()
    .then(function () {
      // Inserts seed entries
      return knex('music').insert([
        {id: 1, playlist_id: 1, song: "All The Small Things", artist: "blink-182"},
        {id: 2, playlist_id: 1, song: "American Idiot", artist: "Green Day"},
        {id: 3, playlist_id: 1, song: "Sk8er Boi", artist: "Avril Lavigne"},
        {id: 4, playlist_id: 1, song: "Figuring It Out", artist: "SWMRS"},
        {id: 5, playlist_id: 1, song: "Doze Off", artist: "Mt.Eddy"},
        {id: 6, playlist_id: 1, song: "Complicated", artist: "Avril Lavigne"},
        {id: 7, playlist_id: 1, song: "Sober", artist: "FIDLAR"},
        {id: 8, playlist_id: 1, song: "Orange", artist: "Mt.Eddy"},
        {id: 9, playlist_id: 1, song: "By Myself", artist: "FIDLAR"},
        {id: 10, playlist_id: 1, song: "Scott Green", artist: "Dune Rats"},
        {id: 11, playlist_id: 1, song: "Don't Try", artist: "Jakob Danger"},
        {id: 12, playlist_id: 1, song: "I Luv Robert Smith", artist: "Mt. Eddy"},
        {id: 13, playlist_id: 1, song: "Hey Now", artist: "The Regrettes"},
        {id: 14, playlist_id: 1, song: "Lose Lose Lose", artist: "SWMRS"},
        {id: 15, playlist_id: 1, song: "Lovely", artist: "Mt. Eddy"},
        {id: 16, playlist_id: 1, song: "Brb", artist: "SWMRS"},
        {id: 17, playlist_id: 1, song: "Trashbag Baby", artist: "SWMRS"},
        {id: 18, playlist_id: 1, song: "Wake Bake Skate", artist: "FIDLAR"},
        {id: 19, playlist_id: 1, song: "Zombie", artist: "Mt. Eddy"},
        {id: 20, playlist_id: 1, song: "Stay the Night - Demo", artist: "Green Day"},
        {id: 21, playlist_id: 2, song: "Fireflies", artist: "Owl City"},
        {id: 22, playlist_id: 2, song: "Valerie (feat. Amy Winehouse) - Version Revisited", artist: "Mark Ronson, Amy Winehouse"},
        {id: 23, playlist_id: 2, song: "Party In The U.S.A", artist: "Miley Cyrus"},
        {id: 24, playlist_id: 2, song: "What Makes You Beautiful", artist: "One Direction"},
        {id: 25, playlist_id: 2, song: "We're All In This Together - From Highschool Musical/Soundtrack Version", artist: "High School Musical Cast"},
        {id: 26, playlist_id: 2, song: "One Thing", artist: "One Direction"},
        {id: 27, playlist_id: 2, song: "Live While We're Young", artist: "One Direction"},
        {id: 28, playlist_id: 2, song: "I Think We're Alone Now", artist: "Tiffany"},
        {id: 29, playlist_id: 2, song: "Payphone", artist: "Maroon 5, Wiz Khalifa"},
        {id: 30, playlist_id: 2, song: "Stick to the Status Quo - From Highschool Musical/Soundtrack Version", artist: "High School Musical Cast, David Lawrence"},
        {id: 31, playlist_id: 2, song: "Bet On It - From High School Musical/Soundtrack Version", artist: "Troy"},
        {id: 32, playlist_id: 2, song: "Best Song Ever", artist: "One Direction"},
        {id: 33, playlist_id: 2, song: "The Climb", artist: "Miley Cyrus"},
        {id: 34, playlist_id: 2, song: "Hot N Cold", artist: "Katy Perry"},
        {id: 35, playlist_id: 2, song: "Just The Way You Are", artist: "Bruno Mars"},
        {id: 36, playlist_id: 2, song: "The Best of Both Worlds - From Hannah Montana/Soundtrack Version", artist: "Hannah Montana"},
        {id: 37, playlist_id: 2, song: "Hey There Delilah", artist: "Plain White T's"},
        {id: 38, playlist_id: 2, song: "All Star", artist: "Smash Mouth"},
        {id: 39, playlist_id: 2, song: "Midnight Memories", artist: "One Direction"},
        {id: 40, playlist_id: 2, song: "Breaking Free - From Highschool Musical/Soundtrack Version", artist: "Troy, Gabriella Montez"},
        {id: 41, playlist_id: 3, song: "Alright", artist: "Supergrass"},
        {id: 42, playlist_id: 3, song: "Parklife - 2012 Remaster", artist: "Blur"},
        {id: 43, playlist_id: 3, song: "Bitter Sweet Symphony", artist: "The Verve"},
        {id: 44, playlist_id: 3, song: "Common People", artist: "Pulp"},
        {id: 45, playlist_id: 3, song: "Country House - 2012 Remaster", artist: "Blur"},
        {id: 46, playlist_id: 3, song: "Don't Look Back in Anger - Remaster", artist: "Oasis"},
        {id: 47, playlist_id: 3, song: "The Drugs Don't Work", artist: "The Verve"},
        {id: 48, playlist_id: 3, song: "Disco 2000", artist: "Pulp"},
        {id: 49, playlist_id: 3, song: "Lucky Man", artist: "The Verve"},
        {id: 50, playlist_id: 3, song: "Creep", artist: "Radiohead"},
        {id: 51, playlist_id: 3, song: "A Song For The Lovers", artist: "Richard Ashcroft"},
        {id: 52, playlist_id: 3, song: "Sun Hits The Sky", artist: "Supergrass"},
        {id: 53, playlist_id: 3, song: "Girl From Mars", artist: "Ash"},
        {id: 54, playlist_id: 3, song: "Charmless Man", artist: "Blur"},
        {id: 55, playlist_id: 3, song: "Mardy Bum", artist: "Arctic Monkeys"},
        {id: 56, playlist_id: 3, song: "Live Forever", artist: "Oasis"},
        {id: 57, playlist_id: 3, song: "Coffee and TV", artist: "Blur"},
        {id: 58, playlist_id: 3, song: "Champagne Supernova - Remastered", artist: "Oasis"},
        {id: 59, playlist_id: 3, song: "Karma Police", artist: "Radiohead"},
        {id: 60, playlist_id: 3, song: "Come Back To Me", artist: "Liam Gallagher"},
        {id: 61, playlist_id: 4, song: "Life on Mars? - 2015 Remaster", artist: "David Bowie"},
        {id: 62, playlist_id: 4, song: "Modern Love - 1999 Remaster", artist: "David Bowie"},
        {id: 63, playlist_id: 4, song: "We Are The Champions - Remastered 2011", artist: "Queen"},
        {id: 64, playlist_id: 4, song: "Crazy Little Thing Called Love - Remastered 2011", artist: "Queen"},
        {id: 65, playlist_id: 4, song: "The Kids Are Alright", artist: "The Who"},
        {id: 66, playlist_id: 4, song: "Wonderwall - Remastered", artist: "Oasis"},
        {id: 67, playlist_id: 4, song: "Bad Moon Rising", artist: "Creedence Clearwater Revival"},
        {id: 68, playlist_id: 4, song: "Rip This Joint", artist: "The Rolling Stones"},
        {id: 69, playlist_id: 4, song: "Like A Rolling Stone - Edit", artist: "The Rolling Stones"},
        {id: 70, playlist_id: 4, song: "She Loves You - Mono/Remastered", artist: "The Beatles"},
        {id: 71, playlist_id: 4, song: "Get Back - Remastered", artist: "The Beatles"},
        {id: 72, playlist_id: 4, song: "Working Class Hero - Remastered 2010/Lennon Legend Version", artist: "John Lennon"},
        {id: 73, playlist_id: 4, song: "Purple Haze", artist: "Jimi Hendrix"},
        {id: 74, playlist_id: 4, song: "Boys Don't Cry", artist: "The Cure"},
        {id: 75, playlist_id: 4, song: "Everlong", artist: "Foo Fighters"},
        {id: 76, playlist_id: 4, song: "Walk", artist: "Foo Fighters"},
        {id: 77, playlist_id: 4, song: "You Really Got Me - Mono Mix", artist: "The Kinks"},
        {id: 78, playlist_id: 4, song: "The Chain - 2004 Remaster", artist: "Fleetwood Mac"},
        {id: 79, playlist_id: 4, song: "Can't Stop", artist: "Red Hot Chilli Peppers"},
        {id: 80, playlist_id: 4, song: "Shockwave", artist: "Liam Gallagher"},
        {id: 81, playlist_id: 5, song: "Do You Hear The People Sing?", artist: "Les Misérables Cast"},
        {id: 82, playlist_id: 5, song: "This is Me", artist: "The Greatest Showman Cast"},
        {id: 83, playlist_id: 5, song: "Jesus of Suburbia", artist: "American Idiot Cast"},
        {id: 84, playlist_id: 5, song: "The Worst Pies in London", artist: "Sweeney Todd Cast"},
        {id: 85, playlist_id: 5, song: "No Place Like London", artist: "Sweeney Todd Cast"},
        {id: 86, playlist_id: 5, song: "Last of the American Girls / She's a Rebel", artist: "American Idiot Cast"},
        {id: 87, playlist_id: 5, song: "Life On Mars?", artist: "Lazarus Cast"},
        {id: 88, playlist_id: 5, song: "When It's Time", artist: "American Idiot Cast"},
        {id: 89, playlist_id: 5, song: "The Greatest Show", artist: "The Greatest Showman Cast"},
        {id: 90, playlist_id: 5, song: "Breaking Free", artist: "High School Musical Cast"},
        {id: 91, playlist_id: 5, song: "What I've Been Looking For", artist: "High School Musical Cast"},
        {id: 92, playlist_id: 5, song: "You Are The Music in Me", artist: "High School Musical 2 Cast"},
        {id: 93, playlist_id: 5, song: "Beautiful", artist: "Heathers Cast"},
        {id: 94, playlist_id: 5, song: "Dead Girl Walking", artist: "Heathers Cast"},
        {id: 95, playlist_id: 5, song: "The Other Side", artist: "The Greatest Showman Cast"},
        {id: 96, playlist_id: 5, song: "Bui Doi", artist: "Miss Saigon Cast"},
        {id: 97, playlist_id: 5, song: "Johanna", artist: "Sweeney Todd Cast"},
        {id: 98, playlist_id: 5, song: "School of Rock", artist: "School Of Rock Cast"},
        {id: 99, playlist_id: 5, song: "You're in the Band", artist: "School Of Rock Cast"},
        {id: 100, playlist_id: 5, song: "Too Much Too Soon", artist: "American Idiot Cast"},
        {id: 101, playlist_id: 6, song: "Reptillia", artist: "The Strokes"},
        {id: 102, playlist_id: 6, song: "Fluorescent Adolescent", artist: "Arctic Monkeys"},
        {id: 103, playlist_id: 6, song: "A-Punk", artist: "Vampire Weekend"},
        {id: 104, playlist_id: 6, song: "Naive", artist: "The Kooks"},
        {id: 105, playlist_id: 6, song: "Last Nite", artist: "The Strokes"},
        {id: 106, playlist_id: 6, song: "Seven Nation Army", artist: "The White Stripes"},
        {id: 107, playlist_id: 6, song: "Machu Picchu", artist: "The Strokes"},
        {id: 108, playlist_id: 6, song: "Human", artist: "The Killers"},
        {id: 109, playlist_id: 6, song: "She Moves In Her Own Way", artist: "The Kooks"},
        {id: 110, playlist_id: 6, song: "Kids", artist: "MGMT"},
        {id: 111, playlist_id: 6, song: "I Bet You Look Good On The Dancefloor", artist: "Arctic Monkeys"},
        {id: 112, playlist_id: 6, song: "Somebody Told Me", artist: "The Killers"},
        {id: 113, playlist_id: 6, song: "Fell In Love With A Girl", artist: "The White Stripes"},
        {id: 114, playlist_id: 6, song: "12:51", artist: "The Strokes"},
        {id: 115, playlist_id: 6, song: "Elephant", artist: "Tame Impala"},
        {id: 116, playlist_id: 6, song: "Here It Goes Again", artist: "OK Go"},
        {id: 117, playlist_id: 6, song: "Lightning Bolt", artist: "Jake Bugg"},
        {id: 118, playlist_id: 6, song: "Crying Lightning", artist: "Arctic Monkeys"},
        {id: 119, playlist_id: 6, song: "Mardy Bum", artist: "Arctic Monkeys"},
        {id: 120, playlist_id: 6, song: "Do You Want To", artist: "Franz Ferdinand"},
        {id: 121, playlist_id: 7, song: "Hakuna Matata", artist: "The Lion King"},
        {id: 122, playlist_id: 7, song: "I Wan'na Be Like You", artist: "The Jungle Book"},
        {id: 123, playlist_id: 7, song: "Can You Feel the Love Tonight", artist: "The Lion King"},
        {id: 124, playlist_id: 7, song: "The Bare Necessities", artist: "The Jungle Book"},
        {id: 125, playlist_id: 7, song: "A Whole New World", artist: "Aladdin"},
        {id: 126, playlist_id: 7, song: "I Just Can't Wait to Be King", artist: "The Lion King"},
        {id: 127, playlist_id: 7, song: "Friend Like Me", artist: "Aladdin"},
        {id: 128, playlist_id: 7, song: "I'll Make a Man Out of You", artist: "Mulan"},
        {id: 129, playlist_id: 7, song: "Kiss the Girl", artist: "The Little Mermaid"},
        {id: 130, playlist_id: 7, song: "Start of Something New", artist: "High School Musical"},
        {id: 131, playlist_id: 7, song: "Go the Distance", artist: "Hercules"},
        {id: 132, playlist_id: 7, song: "Reflection", artist: "Mulan"},
        {id: 133, playlist_id: 7, song: "Gotta Go My Own Way", artist: "High School Musical 2"},
        {id: 134, playlist_id: 7, song: "Dig a Little Deeper", artist: "The Princess and the Frog"},
        {id: 135, playlist_id: 7, song: "Love Is an Open Door", artist: "Frozen"},
        {id: 136, playlist_id: 7, song: "Now Or Never", artist: "High School Musical 3"},
        {id: 137, playlist_id: 7, song: "Be Our Guest", artist: "Beauty and the Beast"},
        {id: 138, playlist_id: 7, song: "High School Musical", artist: "High School Musical 3"},
        {id: 139, playlist_id: 7, song: "Introducing Me", artist: "Camp Rock 2"},
        {id: 140, playlist_id: 7, song: "I Don't Dance", artist: "High School Musical 2"},  
        {id: 141, playlist_id: 8, song: "Going To Pasalaqua", artist: "Green Day"},
        {id: 142, playlist_id: 8, song: "About A Girl - Remastered", artist: "Nirvana"},
        {id: 143, playlist_id: 8, song: "God Save The Queen", artist: "Sex Pistols"},
        {id: 144, playlist_id: 8, song: "Blitzkrieg Bop - 2016 Remaster", artist: "Ramones"},
        {id: 145, playlist_id: 8, song: "Basket Case", artist: "Green Day"},
        {id: 146, playlist_id: 8, song: "Drain You", artist: "Nirvana"},
        {id: 147, playlist_id: 8, song: "Ever Fallen in Love (With Someone You Shouldn't've?", artist: "Buzzcocks"},
        {id: 148, playlist_id: 8, song: "In The City", artist: "The Jam"},
        {id: 149, playlist_id: 8, song: "Territorial Pissings", artist: "Nirvana"},
        {id: 150, playlist_id: 8, song: "White Riot", artist: "The Clash"},
        {id: 151, playlist_id: 8, song: "Who Wrote Holden Caulfield?", artist: "Green Day"},
        {id: 152, playlist_id: 8, song: "What Do I Get? - 2001 Remastered Version", artist: "Buzzcocks"},
        {id: 153, playlist_id: 8, song: "I Wanna Be Your Dog", artist: "The Stooges"},
        {id: 154, playlist_id: 8, song: "Town Called Malice", artist: "The Jam"},
        {id: 155, playlist_id: 8, song: "Knowledge", artist: "Operation Ivy"},
        {id: 156, playlist_id: 8, song: "Welcome to Paradise", artist: "Green Day"},
        {id: 157, playlist_id: 8, song: "In Bloom - Nevermind Version", artist: "Nirvana"},
        {id: 158, playlist_id: 8, song: "Anarchy In The UK", artist: "Sex Pistols"},
        {id: 159, playlist_id: 8, song: "California Uber Alles", artist: "Dead Kennedys"},
        {id: 160, playlist_id: 8, song: "Waiting", artist: "Green Day"},
        {id: 161, playlist_id: 9, song: "Say It Ain't So", artist: "Weezer"},
        {id: 162, playlist_id: 9, song: "The Middle", artist: "Jimmy Eat World"},
        {id: 163, playlist_id: 9, song: "Under the Bridge", artist: "Red Hot Chilli Peppers"},
        {id: 164, playlist_id: 9, song: "Inbetween Days", artist: "The Cure"},
        {id: 165, playlist_id: 9, song: "Buddy Holly", artist: "Weezer"},
        {id: 166, playlist_id: 9, song: "Creep", artist: "Radiohead"},
        {id: 167, playlist_id: 9, song: "Mr. Jones", artist: "Counting Crows"},
        {id: 168, playlist_id: 9, song: "Stacy's Mom", artist: "Fountains Of Wayne"},
        {id: 169, playlist_id: 9, song: "Why'd You Only Call Me When You're High", artist: "Arctic Monkeys"},
        {id: 170, playlist_id: 9, song: "Lonely Boy", artist: "The Black Keys"},
        {id: 171, playlist_id: 9, song: "Someday", artist: "The Strokes"},
        {id: 172, playlist_id: 9, song: "Heart-Shaped Box", artist: "Nirvana"},
        {id: 173, playlist_id: 9, song: "Are You Gonna Be My Girl", artist: "Jet"},
        {id: 174, playlist_id: 9, song: "A-Punk", artist: "Vampire Weekend"},
        {id: 175, playlist_id: 9, song: "Do I Wanna Know?", artist: "Arctic Monkeys"},
        {id: 176, playlist_id: 9, song: "Here It Goes Again", artist: "OK Go"},
        {id: 177, playlist_id: 9, song: "Blister In The Sun", artist: "Violent Femmes"},
        {id: 178, playlist_id: 9, song: "Jerk It Out", artist: "Caesars"},
        {id: 179, playlist_id: 9, song: "Oxford Comma", artist: "Vampire Weekend"},
        {id: 180, playlist_id: 9, song: "Boys Don't Cry", artist: "The Cure"},
      ]);
    });
};
